# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-NL-Numbers-GroeneBoekje
version:      0.01
version_from: lib/Lingua/NL/Numbers/GroeneBoekje.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
